version: 1
CurrentProfileName: Unity-GameLift integraion
CurrentRegion: eu-west-1
CurrentBucketName: gamelift-bootstrap-023196572641-eu-west-1
LastOpenTab: Anywhere
UserProfiles: >+
  - Region: eu-west-1

    Name: Unity-GameLift integraion

    BucketName: gamelift-bootstrap-023196572641-eu-west-1

    AnywhereFleetName: Bino-Game-AnywhereFleet

    AnywhereFleetId: fleet-513bd2ac-b407-431e-9d70-06988be2dc34

    AnywhereFleetLocation: custom-location-1

    ComputeName: PC-3-Unity-GameLift-Bino-Game

    IpAddress: 127.0.0.1

    WebSocketUrl: wss://eu-west-1.api.amazongamelift.com

    DeploymentScenario: SingleRegion

    DeploymentGameName: 

    ManagedEC2FleetName: 

    BuildName: 

    LaunchParameters: 

    BuildOperatingSystem: 

    DeploymentBuildFilePath: 

    DeploymentBuildFolderPath: 

...
