version: 1
LastOpenTab: ManagedEC2
CurrentProfileName: Unity-GameLift integraion
CurrentRegion: eu-west-1
UserProfiles: >+
  - Region: eu-west-1

    Name: Unity-GameLift integraion

    BucketName: gamelift-bootstrap-023196572641-eu-west-1

    AnywhereFleetName: Bino-Game-AnywhereFleet

    AnywhereFleetId: fleet-513bd2ac-b407-431e-9d70-06988be2dc34

    AnywhereFleetLocation: custom-location-1

    ComputeName: PC-3-Unity-GameLift-Bino-Game

    IpAddress: 127.0.0.1

    WebSocketUrl: wss://eu-west-1.api.amazongamelift.com

    DeploymentScenario: SingleRegion

    DeploymentGameName: Bino-Game

    ManagedEC2FleetName: Bino-Game-Fleet

    BuildName: Bino-Game-Single-Region-Build-0.1.1

    LaunchParameters: ''

    BuildOperatingSystem: AMAZON_LINUX_2023

    DeploymentBuildFilePath: C:/Active Projects/Personal/DevOps/Int DevOps Course/Unity-GameLift/Bino-Game-Unity/Builds/Server Builds/Bino-Game-Single-Region-Build-0.1.1/Bino-Game-Server.x86_64

    DeploymentBuildFolderPath: C:/Active Projects/Personal/DevOps/Int DevOps Course/Unity-GameLift/Bino-Game-Unity/Builds/Server Builds/Bino-Game-Single-Region-Build-0.1.1

CurrentBucketName: gamelift-bootstrap-023196572641-eu-west-1
...
